# Generated by Django 2.1.4 on 2022-08-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='creation_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
