# Generated by Django 2.1.4 on 2022-08-16 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_news', '0002_news_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creation_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
