# Generated by Django 2.1.4 on 2022-08-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_news', '0003_auto_20220816_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creation_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
