# Generated by Django 2.1.4 on 2022-08-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_news', '0004_auto_20220816_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
