# Generated by Django 2.1.4 on 2022-08-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_news', '0005_auto_20220817_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
