# Generated by Django 2.1.4 on 2022-08-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_news', '0006_auto_20220818_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
