# Generated by Django 2.1.4 on 2022-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_news', '0007_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
